#!/usr/bin/env bash
# configuration of the subdomains
function audit_subdomain {
  domain=$1
  subdomain=${2:-www lb-01 web-01 web-02}

  for sub in $subdomain; do
    record=$(dig +short $sub.$domain)
    if [ -n "$record" ]; then
      type=$(dig +short $sub.$domain | awk '{print $4}')
      dest=$(dig +short $sub.$domain | awk '{print $1}')
      echo "The subdomain $sub is a $type record and points to $dest"
    fi
  done
}
audit_subdomain $1
