#!/usr/bin/env bash
# this script installs and configures an new ubuntu machine to have HA proxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*
str1="backend mybackend\n\tbalance roundrobin\n\tserver 115044-web-01 100.25.143.38 check\n\tserver 115044-web-02 52.87.219.217 check"
str2="frontend myfrontend\n\tbind *:80\n\tmode http\n\tdefault_backend mybackend"
sudo sed -i "s/backend/$str1/" /etc/haproxy/haproxy.cfg
sudo sed -i "s/frontend/$str2/" /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo systemctl start haproxy
sudo systemctl enable haproxy
