#!/usr/bin/env bash
# this script installs and configures an new ubuntu machine to have HA proxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*
str1=\
"backend myback
	balance roundrobin
	server 115044-web-01 100.25.143.38 check
	server 115044-web-02 52.87.219.217 check
frontend myfront
	bind *:80
	mode http
	default_backend myback
"
echo "$str1" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" |sudo tee -a /etc/default/haproxy
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
