#!/usr/bin/env bash
# doing the same thing just fewer lines
chmod 655 /etc/nginx/nginx.conf
sed -i "s/# user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx /bin/bash -c "service nginx start"
